# Generated by Django 5.1.6 on 2025-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issue_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('issue_key', models.CharField(max_length=50, null=True, unique=True)),
                ('created_date', models.DateTimeField()),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
