# Generated by Django 5.1.6 on 2025-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issues_id_alter_issues_issue_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('hash_commit', models.CharField(max_length=50)),
                ('merge', models.BooleanField(verbose_name='merger status')),
            ],
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
    ]
