# Generated by Django 5.1.6 on 2025-02-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commits_delete_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=50)),
                ('issue_key', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Commits',
        ),
    ]
