# Generated by Django 5.1.6 on 2025-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrychart', '0002_commits_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='added_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commits',
            name='deleted_lines',
            field=models.IntegerField(default=0),
        ),
    ]
