# Generated by Django 5.1.6 on 2025-02-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrychart', '0003_alter_commits_added_lines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='created_dates',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
