# Generated by Django 5.1.6 on 2025-02-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrychart', '0005_alter_commits_created_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='created_dates',
            field=models.DateField(),
        ),
    ]
